ScoutSluzba.Web/Areas/Scout/Controllers/OcjeneiKomentariController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Prodaja_Softvera_ver3.Web.Helper;
using ScoutSluzba.Data;
using ScoutSluzba.Data.EntityModels;
using ScoutSluzba.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScoutSluzba.Web.Controllers
{
    [Area("Scout")]
    public class OcjeneiKomentariController : Controller
    {

        private MyContext _context;

        public OcjeneiKomentariController(MyContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            if (korisnik.TipKorisnickogNaloga != "Zaposlenik")
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa!";
                return RedirectToAction("Index", "Login");
            }

            var model = new OcjeneiKomentariIndexVM
            {
                row = _context.OcjenaKomentar
               .Select(x => new OcjeneiKomentariIndexVM.Row
               {
                   OcjenaKomentarID = x.OcjenaKomentarID,
                   Ocjena = x.Ocjena,
                   Komentar = x.Komentar,
                   ZaposlenikID = x.ZaposlenikID,
                   //Zaposlenik = _context.Zaposlenik.Find(x.ZaposlenikID).Ime + ' '+ _context.Zaposlenik.Find(x.ZaposlenikID).Prezime,
                   IgracID = x.IgracID,
                   //Igrac = _context.Igrac.Find(x.IgracID).Ime + ' ' + _context.Igrac.Find(x.IgracID).Prezime

               })
               .ToList()
            };

            return View(model);
        }


        public IActionResult Dodaj()
        {
            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            if (korisnik.TipKorisnickogNaloga != "Zaposlenik")
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa!";
                return RedirectToAction("Index", "Login");
            }

            var model = new OcjeneiKomentariDodajVM();

            model.Zaposlenik = _context.Zaposlenik.Select(x => new SelectListItem
            {
                Value = x.ZaposlenikID.ToString(),
                Text = x.Ime +' '+ x.Prezime
            }).ToList();

            model.Igrac = _context.Igrac.Select(x => new SelectListItem
            {
                Value = x.IgracID.ToString(),
                Text = x.Ime + ' ' + x.Prezime
            }).ToList();


            return View(model);
        }


        public IActionResult Uredi(int id)
        {
            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            if (korisnik.TipKorisnickogNaloga != "Zaposlenik")
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa!";
                return RedirectToAction("Index", "Login");
            }

            var pronadji = _context.OcjenaKomentar.Find(id);

            var zaposlenik = _context.Zaposlenik.Find(pronadji.ZaposlenikID);
            var igrac = _context.Igrac.Find(pronadji.IgracID);
            var model = new OcjeneiKomentariUrediVM
            {
                OcjenaKomentarID = id,
                Ocjena = pronadji.Ocjena,
                Komentar = pronadji.Komentar,
                Zaposlenik = pronadji.Zaposlenik.Ime + " " + pronadji.Zaposlenik.Prezime,
                Igrac = pronadji.Igrac.Ime + " " + pronadji.Igrac.Prezime
             };

            return View(model);
        }

        public IActionResult Obrisi(int Id)
        {
            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            if (korisnik.TipKorisnickogNaloga != "Zaposlenik")
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa!";
                return RedirectToAction("Index", "Login");
            }

            var z = _context.OcjenaKomentar.Find(Id);
            //var kn = _context.korisnickiNalog.Where(x => x.KorisnickiNalogID == z.KorisnickiNalogID).FirstOrDefault();
            if (z == null)
            {
                TempData["porukaError"] = "Greška pri brisanju Ocjene i komentara!!!";
            }
            else
            {
                _context.Remove(z);
                //_context.Remove(kn);
                _context.SaveChanges();
                TempData["porukaSuccess"] = "Uspjesno ste obrisali Ocjene i komentara!";
            }

            _context.Dispose();
            return RedirectToAction(nameof(Index));
        }

    }
}

ScoutSluzba.Web/Areas/Scout/Views/OcjeneiKomentari/Dodaj.cshtml
@using ScoutSluzba.Web.ViewModels
@model ScoutSluzba.Web.ViewModels.OcjeneiKomentariDodajVM

@{
    ViewData["Title"] = "Dodaj";
}


<div class="content-wrapper p-4">
    <h1 class="text-center"> Edit Comment and Grade: </h1>

    <form asp-action="Snimi">
        <input asp-for="OcjenaKomentarID" hidden />

        <div class="form-group">

            <div>
                @Html.HiddenFor(s => s.OcjenaKomentarID)
            </div>

            <div class="form-group">
                <label>Grade: </label>
                <input asp-for="Ocjena" class="form-control" />
                <span asp-validation-for="Ocjena" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Comment: </label>
                <input asp-for="Komentar" class="form-control" />
                <span asp-validation-for="Komentar" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Employee: </label>
                <select asp-for="ZaposlenikID" asp-items="Model.Zaposlenik" class="form-control"></select>
                <span asp-validation-for="ZaposlenikID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Player: </label>
                <select asp-for="IgracID" asp-items="Model.Igrac" class="form-control"></select>
                <span asp-validation-for="IgracID" class="text-danger"></span>
            </div>

            <a asp-action="Index" asp-controller="OcjeneiKomentari" asp-area="Scout" class="btn btn-outline-info btn-lg"> Back </a>

            <input type="submit" class="btn btn-outline-success btn-lg" value="Save" />
        </div>
    </form>
</div>

ScoutSluzba.Web/Areas/Scout/Views/OcjeneiKomentari/Index.cshtml
@using ScoutSluzba.Web.ViewModels
@*@using ScoutSluzba.Web.Areas.Scout.ViewModels*@

@{
    string error_poruka = (string)TempData["error_poruka"];
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Scout/Views/Shared/_Layout.cshtml";
}

<h1>Comment and Grade</h1>

<table class="table table-hover">
    <thead class="thead-light">
        <tr>
            <th>Grade</th>
            <th>Comment</th>
            <th>Employee</th>
            <th>Player</th>
            <th>Action</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.row)
        {
            <tr>
                <td>@x.Ocjena</td>
                <td>@x.Komentar</td>
                <td>@x.Zaposlenik</td>
                <td>@x.Igrac</td>
                <td>
                    <a asp-action="Obrisi" asp-controller="OcjeneiKomentari" asp-area="Scout" asp-route-id="@x.OcjenaKomentarID" class="btn btn-outline-danger btn-sm"><i class="fa fa-trash"></i></a>

                    <a asp-action="Uredi" asp-controller="OcjeneiKomentari" asp-area="Scout" asp-route-id="@x.OcjenaKomentarID" class="btn btn-outline-info btn-sm"><i class="fa fa-pen"></i></a>
                </td>
            </tr>

        }
    </tbody>
</table>

<a asp-action="Dodaj" asp-controller="OcjeneiKomentari" asp-area="Scout" class="btn btn-outline-success btn-lg"> Add Comment and Grade </a>


@if (error_poruka != null)
{
    <br />
    <div class="alert alert-danger" role="alert">
        <strong>@error_poruka</strong>
    </div>
}

ScoutSluzba.Web/Areas/Scout/Views/OcjeneiKomentari/Uredi.cshtml
@model ScoutSluzba.Web.ViewModels.OcjeneiKomentariUrediVM
@using ScoutSluzba.Web.ViewModels;
@using ScoutSluzba.Data.EntityModels;


@{
    ViewData["Title"] = "Uredi";
}


<div class="content-wrapper p-4">
    <h1 class="display-4">Edit Grade and Comment</h1>

    <form asp-action="Snimi">
        <input asp-for="OcjenaKomentarID" hidden />

        <div class="form-group">

            <div class="form-group">
                <label>Grade</label>
                <input asp-for="Ocjena" class="form-control" readonly />
                <span asp-validation-for="Ocjena" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Comment</label>
                <input asp-for="Komentar" class="form-control" readonly />
                <span asp-validation-for="Komentar" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label>Employee </label>
                <input asp-for="Zaposlenik" class="form-control" readonly />
                <span asp-validation-for="Zaposlenik" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Player </label>
                <input asp-for="Igrac" class="form-control" readonly />
                <span asp-validation-for="Igrac" class="text-danger"></span>
            </div>

            <a asp-action="Index" asp-controller="OcjeneiKomentari" asp-area="Scout" class="btn btn-outline-info btn-lg"> Back </a>

           @* <input type="submit" class="btn btn-success btn-lg" value="Snimi" />*@

        </div>
    </form>
</div>