ScoutSluzba.Web/Areas/AdminModul/Controllers/TimoviController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Prodaja_Softvera_ver3.Web.Helper;
using ScoutSluzba.Data;
using ScoutSluzba.Data.EntityModels;
using ScoutSluzba.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScoutSluzba.Web.Controllers
{
    [Area("AdminModul")]
    public class TimoviController : Controller
    {
        private MyContext _context;
        public TimoviController(MyContext context)
        {
            _context = context;
        }


        public IActionResult Index(int pageNumber = 1, int pageSize = 5)
        {

            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            if (korisnik.TipKorisnickogNaloga != "Administartor")
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa!";
                return RedirectToAction("Index", "Login");
            }

            var model = new TimoviIndexVM
            {
                rows = _context.Team
             .Select(x => new TimoviIndexVM.Row
             {
                 TimID = x.TeamID,
                 Naziv = x.Naziv,
                 Trener = x.Trener,
                 Stadion = x.Stadion,
                 Manager = x.Manager,
                 Predsjednik = x.President,
                 Lokacija = x.Lokacija,
                 Slika = x.Slika

                }).ToList()
            };
            return View(model);

          //  var path = Path.Combine(
          //           Directory.GetCurrentDirectory(), "wwwroot/Slike",
          //           "ae.png");


          //  byte[] imageArray = System.IO.File.ReadAllBytes(path);
          //  string imageBase64 = Convert.ToBase64String(imageArray);



          //  List<Softver> softveri = _context.Softver.ToList();
          //  ViewBag.Softveri = softveri;


          //  int ExcludeRecords = (pageSize * pageNumber) - pageSize;
          //  var model = new SoftvareKlijentIndexVM();
          //  var result = new PagedResult<SoftvareKlijentIndexVM.Row>();
          //  //var ocjenaTrazi = _context.SoftverNarudzba.Where(x=>x.oc)

          //  model.rows = _context.Softver
          //.Select(x => new SoftvareKlijentIndexVM.Row
          //{
          //    SoftverID = x.SoftverID,
          //    imgfilename = x.imgurl,
          //    Naziv = x.Naziv,
          //    Verzija = x.Verzija,
          //    Cijena = x.Cijena,

          //    Ocjena = (int)_context.SoftverNarudzba.Where(z => z.SoftverID == x.SoftverID)
          //    .Select(z => z.Ocjena).Average(),

          //    Komentar = _context.SoftverNarudzba.OrderByDescending(c => c.Datum)
          //    .Where(z => z.SoftverID == x.SoftverID)
          //    .Select(z => z.Komentar).FirstOrDefault(),

          //    TipSoftvera = x.TipSoftvera.Naziv

          //}).OrderBy(x => x.SoftverID).Skip(ExcludeRecords).Take(pageSize).ToList();

          //  result = new PagedResult<SoftvareKlijentIndexVM.Row>
          //  {
          //      Data = model.rows.ToList(),
          //      TotalItems = _context.Softver.Count(),
          //      PageNumber = pageNumber,
          //      PageSize = pageSize
          //  };

          //  return View(result);
        }




        public IActionResult Info(int id)
        {
             KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            if (korisnik.TipKorisnickogNaloga != "Administartor")
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa!";
                return RedirectToAction("Index", "Login");
            }

            var pronadji = _context.Team.Find(id);
            var Liga = _context.Liga.Find(pronadji.LigaID);
            var model = new TimoviInfoVM
            {
                TimID = id,
                Naziv = pronadji.Naziv,
                Trener = pronadji.Trener,
                Stadion = pronadji.Stadion,
                Manager = pronadji.Manager,
                Predsjednik = pronadji.President,
                Lokacija = pronadji.Lokacija,
                LigaID = Liga.LigaID,
                Liga = Liga.Naziv

            };


            return View(model);
        }



        public IActionResult Dodaj()
        {

            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            if (korisnik.TipKorisnickogNaloga != "Administartor")
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa!";
                return RedirectToAction("Index", "Login");
            }

            var model = new TimoviDodajVM();

            model.Liga = _context.Liga.Select(x => new SelectListItem
            {
                Value = x.LigaID.ToString(),
                Text = x.Naziv
            }).ToList();



            return View(model);
        }




        public IActionResult Obrisi(int Id)
        {
            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            if (korisnik.TipKorisnickogNaloga != "Administartor")
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa!";
                return RedirectToAction("Index", "Login");
            }

            var z = _context.Team.Find(Id);
            //var kn = _context.korisnickiNalog.Where(x => x.KorisnickiNalogID == z.KorisnickiNalogID).FirstOrDefault();
            if (z == null)
            {
                TempData["porukaError"] = "Greška pri brisanju Igraca!!!";
            }
            else
            {
                _context.Remove(z);
                //_context.Remove(kn);
                _context.SaveChanges();
                TempData["porukaSuccess"] = "Uspjesno ste obrisali Igraca!";
            }

            _context.Dispose();
            return RedirectToAction(nameof(Index));
        }








    }
}

ScoutSluzba.Web/Areas/AdminModul/Views/Timovi/Dodaj.cshtml
@using ScoutSluzba.Web.ViewModels
@model ScoutSluzba.Web.ViewModels.TimoviDodajVM

@{
    ViewData["Title"] = "Dodaj";
}

<div class="content-wrapper p-4">
    <h1 class="text-center"> Dodaj Tim: </h1>


    <form asp-action="Snimi">
        <input asp-for="TimID" hidden />

        <div class="form-group">

            <div>
                @Html.HiddenFor(s => s.TimID)
            </div>

            <div class="form-group">
                <label>Name: </label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Trainer: </label>
                <input asp-for="Trener" class="form-control" />
                <span asp-validation-for="Trener" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Stadium: </label>
                <input asp-for="Stadion" class="form-control" />
                <span asp-validation-for="Stadion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Manager: </label>
                <input asp-for="Manager" class="form-control" />
                <span asp-validation-for="Manager" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Chief: </label>
                <input asp-for="Predsjednik" class="form-control" />
                <span asp-validation-for="Predsjednik" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label>Location: </label>
                <input asp-for="Lokacija" class="form-control" />
                <span asp-validation-for="Lokacija" class="text-danger"></span>
            </div>



            <div class="form-group">
                <label>Liga: </label>
                <select asp-for="LigaID" asp-items="Model.Liga" class="form-control"></select>
                <span asp-validation-for="LigaID" class="text-danger"></span>
            </div>

            <a asp-action="Index" asp-controller="Timovi" asp-area="AdminModul" class="btn btn-outline-info btn-lg"> Back </a>
            <input type="submit" class="btn btn-outline-success btn-lg" value="Snimi" />
        </div>
    </form>
</div>

ScoutSluzba.Web/Areas/AdminModul/Views/Timovi/Index.cshtml
@using ScoutSluzba.Web.ViewModels

@{
    ViewData["Title"] = "Index";
}

<h1>Teams</h1>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Slika </th>
            <th>Name</th>
            <th>Trainer</th>
            <th>Stadium</th>
            <th>Manager</th>
            <th>Chief</th>
            <th>Location</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.rows)
        {
            <tr>
                <td><img src="~/Slike/@x.Slika" width="75" height="75" class="img rounded-circle"/></td>

                <td>@x.Naziv</td>
                <td>@x.Trener</td>
                <td>@x.Stadion</td>
                <td>@x.Manager</td>
                <td>@x.Predsjednik</td>
                <td>@x.Lokacija</td>
                <td>
                    <a asp-action="Obrisi" asp-controller="Timovi" asp-area="AdminModul" asp-route-id="@x.TimID" class="btn btn-outline-danger btn-sm"><i class="fa fa-trash"></i></a>

                    <a asp-action="Info" asp-controller="Timovi" asp-area="AdminModul" asp-route-id="@x.TimID" class="btn btn-outline-primary btn-sm"><i class="fa fa-pen"></i></a>

                </td>
            </tr>

        }
    </tbody>
</table>

<a asp-action="Dodaj" asp-controller="Timovi" asp-area="AdminModul" class="btn btn-outline-success btn-lg"> Add Team </a>

ScoutSluzba.Web/Areas/AdminModul/Views/Timovi/Info.cshtml
@model ScoutSluzba.Web.ViewModels.TimoviInfoVM
@using ScoutSluzba.Web.ViewModels;
@using ScoutSluzba.Data.EntityModels;


@{
    ViewData["Title"] = "Info";
}

<div class="content-wrapper p-4">
    <h1 class="display-4">Team Info</h1>

    <form asp-action="Snimi">
        <input asp-for="TimID" hidden />

        <div class="form-group">

            <div class="form-group">
                <label>Name</label>
                <input asp-for="Naziv" class="form-control" readonly />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Trainer</label>
                <input asp-for="Trener" class="form-control" readonly />
                <span asp-validation-for="Trener" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Stadium</label>
                <input asp-for="Stadion" class="form-control" readonly />
                <span asp-validation-for="Stadion" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label>Manager</label>
                <input asp-for="Manager" class="form-control" readonly />
                <span asp-validation-for="Manager" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label>Chief</label>
                <input asp-for="Predsjednik" class="form-control" readonly />
                <span asp-validation-for="Predsjednik" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label>League</label>
                <input asp-for="Liga" class="form-control" readonly />
                <span asp-validation-for="Liga" class="text-danger"></span>
            </div>


            <a asp-action="Index" asp-controller="Timovi" asp-area="AdminModul" class="btn btn-outline-info btn-lg"> Back </a>
        </div>
    </form>
</div>