ScoutSluzba.Web/Areas/Scout/Controllers/OptionsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Prodaja_Softvera_ver3.Web.Helper;
using ScoutSluzba.Data;
using ScoutSluzba.Data.EntityModels;
using ScoutSluzba.Web.Areas.Scout.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScoutSluzba.Web.Areas.Scout.Controllers
{
    [Area("Scout")]
    public class OptionsController : Controller
    {
        private MyContext _context;
        public OptionsController(MyContext context)
        {
            _context = context;
        }


        public IActionResult Index(int id)
        {
            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            if (korisnik.TipKorisnickogNaloga != "Zaposlenik")
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa!";
                return RedirectToAction("Index", "Login");
            }

            var pronadji = _context.Zaposlenik.Find(id);
            var pronadjiGrad = _context.Grad.Find(pronadji.GradID);

            var model = new OptionScoutVM
            {
                ZaposlenikID = pronadji.ZaposlenikID,
                Ime = pronadji.Ime,
                Prezime = pronadji.Prezime,
                Mail = pronadji.Email,
                Kontakt_br = pronadji.Kontakt_br,
                Datum_rodjenja = pronadji.Datum_rodjenja,
                Spol = pronadji.Spol,
                Grad = pronadjiGrad.Naziv
            };
            return View(model);
        }

        public IActionResult Uredi(int id)
        {
            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            if (korisnik.TipKorisnickogNaloga != "Zaposlenik")
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa!";
                return RedirectToAction("Index", "Login");
            }

            var pronadji = _context.Zaposlenik.Find(id);
            var pronadjiGrad = _context.Grad.Find(pronadji.GradID);

            var model = new OptionUrediScoutVM
            {
                ZaposlenikID = pronadji.ZaposlenikID,
                Ime = pronadji.Ime,
                Prezime = pronadji.Prezime,
                Mail = pronadji.Email,
                Kontakt_br = pronadji.Kontakt_br,
                Datum_rodjenja = pronadji.Datum_rodjenja,
                Spol = pronadji.Spol
            };

            model.Grad = _context.Grad.Select(x => new SelectListItem
            {
                Value = x.GradID.ToString(),
                Text = x.Naziv
            }).ToList();

            return View(model);

        }
    }
}

ScoutSluzba.Web/Areas/Scout/Views/Options/Index.cshtml
@using ScoutSluzba.Web.ViewModels

@model ScoutSluzba.Web.Areas.Scout.ViewModels.OptionScoutVM
@{
    string error_poruka = (string)TempData["error_poruka"];
    ViewData["Title"] = "Index";
}

@*<h1>Options</h1>*@


<div class="content-wrapper p-4">
    <h1 class="text-center"> User Profile: </h1> <br />

    <form asp-action="Snimi">
        <input asp-for="ZaposlenikID" hidden />

        <div class="form-group">

            <div>
                @Html.HiddenFor(s => s.ZaposlenikID)
            </div>

            <div class="form-group">
                <label>Name: </label>
                <input asp-for="Ime" class="form-control" readonly />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Surname: </label>
                <input asp-for="Prezime" class="form-control" readonly />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Email: </label>
                <input asp-for="Mail" class="form-control" readonly />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Phone Number: </label>
                <input asp-for="Kontakt_br" class="form-control" readonly />
                <span asp-validation-for="Kontakt_br" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label>Date of Birth: </label>
                <input asp-for="Datum_rodjenja" class="form-control" readonly />
                <span asp-validation-for="Datum_rodjenja" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label>Sex: </label>
                <input asp-for="Spol" class="form-control" readonly />
                <span asp-validation-for="Spol" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>City: </label>
                <input asp-for="Grad" class="form-control" readonly />
                <span asp-validation-for="Grad" class="text-danger"></span>
            </div>

            <a asp-action="Uredi" asp-controller="Options" asp-area="Scout" asp-route-id="@Model.ZaposlenikID" class="btn btn-outline-info btn-lg"> Edit Profile </a>

        </div>
    </form>
</div>

@if (error_poruka != null)
{
    <br />
    <div class="alert alert-danger" role="alert">
        <strong>@error_poruka</strong>
    </div>
}

ScoutSluzba.Web/Areas/Scout/Views/Options/Uredi.cshtml
@using ScoutSluzba.Web.ViewModels

@model ScoutSluzba.Web.Areas.Scout.ViewModels.OptionUrediScoutVM
@{
    ViewData["Title"] = "Index";
}

@*<h1>Options</h1>*@


<div class="content-wrapper p-4">
    <h1 class="text-center"> Edit Your Profile: </h1> <br />

    <form asp-action="Snimi">
        <input asp-for="ZaposlenikID" hidden />

        <div class="form-group">

            <div>
                @Html.HiddenFor(s => s.ZaposlenikID)
            </div>

            <div class="form-group">
                <label>Name: </label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Surname: </label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Email: </label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Phone Number: </label>
                <input asp-for="Kontakt_br" class="form-control" />
                <span asp-validation-for="Kontakt_br" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label>Date of Birth: </label>
                <input asp-for="Datum_rodjenja" class="form-control" />
                <span asp-validation-for="Datum_rodjenja" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label>Sex: </label>
                <input asp-for="Spol" class="form-control" />
                <span asp-validation-for="Spol" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>City: </label>
                <select asp-for="GradID" asp-items="Model.Grad" class="form-control"></select>
                <span asp-validation-for="GradID" class="text-danger"></span>
            </div>

            <a asp-action="Index" asp-controller="Options" asp-area="Scout" asp-route-id="@Model.ZaposlenikID" class="btn btn-outline-info btn-lg"> Back </a>

            <input type="submit" class="btn btn-outline-success btn-lg" value="Save" />

        </div>
    </form>
</div>