ScoutSluzba.Web/Areas/AdminModul/Controllers/IgraciController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Prodaja_Softvera_ver3.Web.Helper;
using ScoutSluzba.Data;
using ScoutSluzba.Data.EntityModels;
using ScoutSluzba.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScoutSluzba.Web.Controllers
{
    [Area("AdminModul")]
    //[Autorizacija(admin: true, zaposlenik: false)]
    public class IgraciController : Controller
    {
        private MyContext _context;

        public IgraciController(MyContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            //KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            //if (korisnik.TipKorisnickogNaloga != "Administartor")
            //{
            //    ViewData["error_poruka"] = "Nemate pravo pristupa!";
            //    return RedirectToAction("Index", "Login");
            //}

            var model = new IgracIndexVM
            {
                igraci = _context.Igrac
                .Select(x => new IgracIndexVM.Row
                {
                    IgracID = x.IgracID,
                    Ime = x.Ime,
                    Prezime = x.Prezime,
                    Visina = x.Visina,
                    Tezina = x.Tezina,
                    DatumRodjenja = x.Datum_rodjenja,
                    GradID = x.GradID,
                    TeamID = x.TeamID,
                    Prosjek = '-',
                    Slike = x.imgurl

                })
                .ToList()
            };

            return View(model);
        }



        //Akcija: Dodaj novog zaposlenika
        public IActionResult Dodaj()
        {
            //KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            //if (korisnik.TipKorisnickogNaloga != "Administartor")
            //{
            //    ViewData["error_poruka"] = "Nemate pravo pristupa!";
            //    return RedirectToAction("Index", "Login");
            //}

            var model = new IgracDodajVM();

            model.Grad = _context.Grad.Select(x => new SelectListItem
            {
                Value = x.GradID.ToString(),
                Text = x.Naziv
            }).ToList();

            //ZA KATEGORIJU I SPECIFIKACIJU TREBA DA SE NAPRAVI NOVA DODAJ FORMA

            //model.Kategorija = _context.Kategorija.Select(x => new SelectListItem
            //{
            //    Value = x.KategorijaID.ToString(),
            //    Text = x.Pozicija
            //}).ToList();


            //model.Specifikacija = _context.Specifikacija.Select(x => new SelectListItem
            //{
            //    Value = x.SpecifikacijaID.ToString(),
            //    Text = x.BrojSlobodnih
            //}).ToList();


            model.Team = _context.Team.Select(x => new SelectListItem
            {
                Value = x.TeamID.ToString(),
                Text = x.Naziv
            }).ToList();


            return View(model);
        }


        ////Akcija: Uredi zaposlenika
        public IActionResult Uredi(int id)
        {
            //KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            //if (korisnik.TipKorisnickogNaloga != "Administartor")
            //{
            //    ViewData["error_poruka"] = "Nemate pravo pristupa!";
            //    return RedirectToAction("Index", "Login");
            //}

            var pronadji = _context.Igrac.Find(id);
            //var Kategorij = new Kategorija();
            //var Specifikacija = new Specifikacija();

            var Kategorij = _context.Kategorija.Find(pronadji.KategorijaID);
            var Specifikacija = _context.Specifikacija.Find(pronadji.SpecifikacijaID);
            var model = new IgracUrediVM
            {
                IgracID = id,
                Ime = pronadji.Ime,
                Prezime = pronadji.Prezime,
                Visina = pronadji.Visina,

                Tezina = pronadji.Tezina,
                Datum_rodjenja = pronadji.Datum_rodjenja,

             

                //kategorija-----------------------------------
                KategorijaID = Kategorij.KategorijaID,
                Oznaka = Kategorij.Oznaka,
                Pozicija = Kategorij.Pozicija,
                Opis = Kategorij.Opis,
                Dob = Kategorij.Dob,
                //------------------------------------------------



                //specifikacija-----------------------------------
                SpecifikacijaID = Specifikacija.SpecifikacijaID,
                BrojPogodaka = Specifikacija.BrojPogodaka,
                BrojKornera = Specifikacija.BrojKornera,
                BrojSlobodnih = Specifikacija.BrojSlobodnih,
                BrOffside = Specifikacija.BrOffside,
                CrveniKarton = Specifikacija.CrveniKarton,
                ZutiKarton = Specifikacija.ZutiKarton,
                //------------------------------------------------

                Grad = _context.Grad.Select(x => new SelectListItem
                {
                    Value = x.GradID.ToString(),
                    Text = x.Naziv
                }).ToList(),



                Team = _context.Team.Select(x => new SelectListItem
                {
                    Value = x.TeamID.ToString(),
                    Text = x.Naziv
                }).ToList()
            };


            return View(model);
        }


        public IActionResult Info(int id)
        {
            //KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            //if (korisnik.TipKorisnickogNaloga != "Administartor")
            //{
            //    ViewData["error_poruka"] = "Nemate pravo pristupa!";
            //    return RedirectToAction("Index", "Login");
            //}

            var pronadji = _context.Igrac.Find(id);
            //var Kategorij = new Kategorija();
            //var Specifikacija = new Specifikacija();

            var Kategorij = _context.Kategorija.Find(pronadji.KategorijaID);
            var Specifikacija = _context.Specifikacija.Find(pronadji.SpecifikacijaID);
            var Grad = _context.Grad.Find(pronadji.GradID);
            var Team = _context.Team.Find(pronadji.TeamID);
            IgracInfoVM model = new IgracInfoVM
            {
                IgracID = id,
                Ime = pronadji.Ime,
                Prezime = pronadji.Prezime,
                Visina = pronadji.Visina,

                Tezina = pronadji.Tezina,
                Datum_rodjenja = pronadji.Datum_rodjenja,



                //kategorija-----------------------------------
                KategorijaID = Kategorij.KategorijaID,
                Oznaka = Kategorij.Oznaka,
                Pozicija = Kategorij.Pozicija,
                Opis = Kategorij.Opis,
                Dob = Kategorij.Dob,
                //------------------------------------------------



                //specifikacija-----------------------------------
                SpecifikacijaID = Specifikacija.SpecifikacijaID,
                BrojPogodaka = Specifikacija.BrojPogodaka,
                BrojKornera = Specifikacija.BrojKornera,
                BrojSlobodnih = Specifikacija.BrojSlobodnih,
                BrOffside = Specifikacija.BrOffside,
                CrveniKarton = Specifikacija.CrveniKarton,
                ZutiKarton = Specifikacija.ZutiKarton,
                //------------------------------------------------

                Grad = Grad.Naziv,
                Team = Team.Naziv
            };


            return View(model);
        }

        //Akcija: Snimi
        //public IActionResult Snimi(IgracDodajVM input)
        //{
        //    Igrac igrac;
        //    if (input.IgracID == 0)
        //    {
        //        igrac = new Igrac();
        //        _context.Add(igrac);
        //    }
        //    else
        //    {
        //        igrac = _context.Zaposlenik.Find(input.ZaposlenikID);
        //    }
        //    igrac.Ime = input.Ime;
        //    igrac.Prezime = input.Prezime;
        //    igrac.Visina = input.Visina;
        //    igrac.Tezina = input.Tezina;
        //    igrac.Datum_rodjenja = input.Datum_rodjenja;
        //    igrac.GradID = input.GradID;

        //    _context.SaveChanges();


        //    KorisnickiNalog kn = new KorisnickiNalog();
        //    if (igrac.KorisnickiNalogID == null)
        //    {
        //        kn.KorisnickoIme = igrac.Ime;
        //        kn.Lozinka = igrac.Ime;
        //        kn.TipKorisnickogNaloga = "Zaposlenik";

        //        _context.korisnickiNalog.Add(kn);
        //        _context.SaveChanges();

        //        //igrac.KorisnickiNalogID = kn.KorisnickiNalogID;

        //        _context.Zaposlenik.Update(igrac);
        //        _context.SaveChanges();
        //    }

        //    _context.Dispose();

        //    TempData["porukaSuccess"] = "Zaposlenik uspjesno dodat!!!";
        //    return RedirectToAction("Index");

        //}


        //Akcija: Obrisi zaposlenika
        public IActionResult Obrisi(int Id)
        {
            //KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            //if (korisnik.TipKorisnickogNaloga != "Administartor")
            //{
            //    ViewData["error_poruka"] = "Nemate pravo pristupa!";
            //    return RedirectToAction("Index", "Login");
            //}

            var z = _context.Igrac.Find(Id);
            //var kn = _context.korisnickiNalog.Where(x => x.KorisnickiNalogID == z.KorisnickiNalogID).FirstOrDefault();
            if (z == null)
            {
                TempData["porukaError"] = "Greška pri brisanju Igraca!!!";
            }
            else
            {
                _context.Remove(z);
                //_context.Remove(kn);
                _context.SaveChanges();
                TempData["porukaSuccess"] = "Uspjesno ste obrisali Igraca!";
            }

            _context.Dispose();

ScoutSluzba.Web/Areas/AdminModul/Views/Igraci/Dodaj.cshtml
@using ScoutSluzba.Web.ViewModels
@model ScoutSluzba.Web.ViewModels.IgracDodajVM

@{
    ViewData["Title"] = "Dodaj";
}



<div class="content-wrapper p-4">
    <h1 class="text-center"> Add Player: </h1>

    <form asp-action="Snimi">
        <input asp-for="IgracID" hidden />

        <div class="form-group">

            <div>
                @Html.HiddenFor(s => s.IgracID)
            </div>

            <div class="form-group">
                <label>Name: </label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Surname: </label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Height: </label>
                <input asp-for="Visina" class="form-control" />
                <span asp-validation-for="Visina" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Weight: </label>
                <input asp-for="Tezina" class="form-control" />
                <span asp-validation-for="Tezina" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Date of Birth: </label>
                <input asp-for="DatumRodjenja" class="form-control" />
                <span asp-validation-for="DatumRodjenja" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label>City: </label>
                <select asp-for="GradID" asp-items="Model.Grad" class="form-control"></select>
                <span asp-validation-for="GradID" class="text-danger"></span>
            </div>



            <div class="form-group">
                <label>Team: </label>
                <select asp-for="TeamID" asp-items="Model.Team" class="form-control"></select>
                <span asp-validation-for="TeamID" class="text-danger"></span>
            </div>

            <a asp-action="Index" asp-controller="Igraci" asp-area="AdminModul" class="btn btn-outline-info btn-lg"> Back </a>
            <input type="submit" class="btn btn-outline-success btn-lg" value="Save" />
        </div>
    </form>
</div>

ScoutSluzba.Web/Areas/AdminModul/Views/Igraci/Index.cshtml
@using ScoutSluzba.Web.ViewModels

@{
    ViewData["Title"] = "Index";
    string error_poruka = (string)TempData["error_poruka"];
    //IgracIndexVM ulazniModel = (IgracIndexVM)ViewData["ulazniModel"];
}

<h1>Players</h1>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Slika</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Height</th>
            <th>Weight</th>
            <th>Date of birth</th>
            <th>City</th>
            <th>Team</th>
            <th>Average</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.igraci)
        {
        <tr>
            <td><img src="~/Slike/@x.Slike" width="95" height="95" class="img rounded-circle" /></td>
            <td>@x.Ime</td>
            <td>@x.Prezime</td>
            <td>@x.Visina</td>
            <td>@x.Tezina</td>
            <td>@x.DatumRodjenja</td>
            <td>@x.Grad</td>
            <td>@x.Team</td>
            <td>@x.Prosjek</td>
            <td>
                <a asp-action="Obrisi" asp-controller="Igraci" asp-area="AdminModul" asp-route-id="@x.IgracID" class="btn btn-outline-danger btn-sm"><i class="fa fa-trash"></i></a>

                <a asp-action="Info" asp-controller="Igraci" asp-area="AdminModul" asp-route-id="@x.IgracID" class="btn btn-outline-info btn-sm"><i class="fa fa-info-circle"></i></a>

                <a asp-action="Uredi" asp-controller="Igraci" asp-area="AdminModul" asp-route-id="@x.IgracID" class="btn btn-outline-primary btn-sm"><i class="fa fa-pen"></i></a>

            </td>
        </tr>

        }
    </tbody>
</table>

<a   asp-action="Dodaj" asp-controller="Igraci" asp-area="AdminModul" class="btn btn-outline-success btn-lg"> Add Player </a>

ScoutSluzba.Web/Areas/AdminModul/Views/Igraci/Info.cshtml
@model ScoutSluzba.Web.ViewModels.IgracInfoVM
@using ScoutSluzba.Web.ViewModels;
@using ScoutSluzba.Data.EntityModels;


@{
    ViewData["Title"] = "Info";
}

<div class="content-wrapper p-4">
    <h1 class="display-4">Player Info</h1>

    <form asp-action="Snimi">
        <input asp-for="IgracID" hidden />

        <div class="form-group">

            <div class="form-group">
                <label>Name</label>
                <input asp-for="Ime" class="form-control" readonly />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Surname</label>
                <input asp-for="Prezime" class="form-control" readonly />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Height</label>
                <input asp-for="Visina" class="form-control" readonly />
                <span asp-validation-for="Visina" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label>Weight</label>
                <input asp-for="Tezina" class="form-control" readonly />
                <span asp-validation-for="Tezina" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label>Date of Birth</label>
                <input asp-for="Datum_rodjenja" class="form-control" readonly />
                <span asp-validation-for="Datum_rodjenja" class="text-danger"></span>

            </div>


            @*kategorija------------------------------------------------------------*@
            <hr>
            <h2 class="display-6"> Category</h2>
            <hr>

            <div class="form-group">
                <label>Mark</label>
                <input asp-for="Oznaka" class="form-control" readonly />
                <span asp-validation-for="Oznaka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Postion</label>
                <input asp-for="Pozicija" class="form-control" readonly />
                <span asp-validation-for="Pozicija" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Description</label>
                <input asp-for="Opis" class="form-control" readonly />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Age</label>
                <input asp-for="Dob" class="form-control" readonly />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>

            @*kategorija------------------------------------------------------------*@



            @*Specifikacija------------------------------------------------------------*@
            <hr>
            <h2 class="display-6"> Specification </h2>
            <hr>

            <div class="form-group">
                <label>Score Number</label>
                <input asp-for="BrojPogodaka" class="form-control" readonly />
                <span asp-validation-for="BrojPogodaka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Corner Number</label>
                <input asp-for="BrojKornera" class="form-control" readonly />
                <span asp-validation-for="BrojKornera" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Free kick Number</label>
                <input asp-for="BrojSlobodnih" class="form-control" readonly />
                <span asp-validation-for="BrojSlobodnih" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Offsides Number</label>
                <input asp-for="BrOffside" class="form-control" readonly />
                <span asp-validation-for="BrOffside" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Red Card</label>
                <input asp-for="CrveniKarton" class="form-control" readonly />
                <span asp-validation-for="CrveniKarton" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Yellow Card</label>
                <input asp-for="ZutiKarton" class="form-control" readonly />
                <span asp-validation-for="ZutiKarton" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>City</label>
                <input asp-for="Grad" class="form-control" readonly />
                <span asp-validation-for="Grad" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label>Team</label>
                <input asp-for="Team" class="form-control" readonly />
                <span asp-validation-for="Team" class="text-danger"></span>
            </div>

            @*Specifikacija------------------------------------------------------------*@


            <a asp-action="Index" asp-controller="Igraci" asp-area="AdminModul" class="btn btn-outline-info btn-lg"> Back </a>


        </div>
    </form>
</div>

ScoutSluzba.Web/Areas/AdminModul/Views/Igraci/Uredi.cshtml
@model ScoutSluzba.Web.ViewModels.IgracUrediVM
@using ScoutSluzba.Web.ViewModels;
@using ScoutSluzba.Data.EntityModels;


@{
    ViewData["Title"] = "Uredi";
}



<div class="content-wrapper p-4">
    <h1 class="display-4">Edit Player</h1>

    <form asp-action="Snimi">
        <input asp-for="IgracID" hidden />

        <div class="form-group">

            <div class="form-group">
                <label>Name</label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Surname</label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Height</label>
                <input asp-for="Visina" class="form-control" />
                <span asp-validation-for="Visina" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label>Weight</label>
                <input asp-for="Tezina" class="form-control" />
                <span asp-validation-for="Tezina" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label>Date of Birth</label>
                <input asp-for="Datum_rodjenja" class="form-control" />
                <span asp-validation-for="Datum_rodjenja" class="text-danger"></span>

            </div>

            @*kategorija------------------------------------------------------------*@
            <hr>
            <h2 class="display-6"> Category</h2>
            <hr>
            <div class="form-group">
                <label>Mark</label>
                <input asp-for="Oznaka" class="form-control" />
                <span asp-validation-for="Oznaka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Postion</label>
                <input asp-for="Pozicija" class="form-control" />
                <span asp-validation-for="Pozicija" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Description</label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Age</label>
                <input asp-for="Dob" class="form-control" />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>

            @*kategorija------------------------------------------------------------*@



            @*Specifikacija------------------------------------------------------------*@
            <hr>
            <h2 class="display-6"> Specification</h2>
            <hr>

            <div class="form-group">
                <label>Score Number</label>
                <input asp-for="BrojPogodaka" class="form-control" />
                <span asp-validation-for="BrojPogodaka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Corner Number</label>
                <input asp-for="BrojKornera" class="form-control" />
                <span asp-validation-for="BrojKornera" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Free kick Number</label>
                <input asp-for="BrojSlobodnih" class="form-control" />
                <span asp-validation-for="BrojSlobodnih" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Offsides Number</label>
                <input asp-for="BrOffside" class="form-control" />
                <span asp-validation-for="BrOffside" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Red Card</label>
                <input asp-for="CrveniKarton" class="form-control" />
                <span asp-validation-for="CrveniKarton" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Yellow Card</label>
                <input asp-for="ZutiKarton" class="form-control" />
                <span asp-validation-for="ZutiKarton" class="text-danger"></span>
            </div>
            @*Specifikacija------------------------------------------------------------*@


            <div class="form-group">
                <label>City </label>
                <select asp-for="GradID" asp-items="Model.Grad" class="form-control"></select>
                <span asp-validation-for="GradID" class="text-danger"></span>

            </div>


            <div class="form-group">
                <label>Team </label>
                <select asp-for="TeamID" asp-items="Model.Team" class="form-control"></select>
                <span asp-validation-for="TeamID" class="text-danger"></span>

            </div>

            <a asp-action="Index" asp-controller="Igraci" asp-area="AdminModul" class="btn btn-outline-info btn-lg"> Back </a>


            <input type="submit" class="btn btn-success btn-lg" value="Snimi" />

        </div>
    </form>
</div>